name: Delete ROSA HCP Cluster

description: |
  This GitHub Action automates the deletion of a ROSA (Red Hat OpenShift Service on AWS) cluster using Terraform.
  This action will also uninstall oc, awscli, rosa cli.

inputs:
  rh-token:
    description: 'Red Hat Hybrid Cloud Console Token'
    required: true
  cluster-name:
    description: 'Name of the ROSA cluster to delete'
    required: true
  aws-region:
    description: 'AWS region where the ROSA cluster is deployed'
    required: true
  s3-backend-bucket:
    description: 'Name of the S3 bucket where the Terraform state is stored'
    required: true
  awscli-version:
    description: 'Version of the aws cli to use'
    required: true
    default: "1.32.105"

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set Terraform variables
      shell: bash
      id: set-terraform-variables
      run: |
        export TFSTATE_BUCKET="${{ inputs.s3-backend-bucket }}"
        export TFSTATE_REGION="${{ inputs.aws-region }}"
        export TFSTATE_KEY="tfstate-${{ inputs.cluster-name }}/${{ inputs.cluster-name }}.tfstate"
        echo "TFSTATE_BUCKET=${TFSTATE_BUCKET}" >> "$GITHUB_OUTPUT"
        echo "TFSTATE_REGION=${TFSTATE_REGION}" >> "$GITHUB_OUTPUT"
        echo "TFSTATE_KEY=${TFSTATE_KEY}" >> "$GITHUB_OUTPUT"

    - name: Terraform Init
      shell: bash
      id: init
      run: |
        cd .github/actions/rosa-delete-cluster/modules/rosa-hcp

        terraform init -backend-config="bucket=${{ steps.set-terraform-variables.outputs.TFSTATE_BUCKET }}" -backend-config="key=${{ steps.set-terraform-variables.outputs.TFSTATE_KEY }}" -backend-config="region=${{ steps.set-terraform-variables.outputs.TFSTATE_REGION }}"
        terraform validate -no-color

    - name: Terraform Plan Destroy
      shell: bash
      id: plan-destroy
      run: |
        cd .github/actions/rosa-delete-cluster/modules/rosa-hcp
        terraform plan -destroy -no-color -out rosa-destroy.plan -var "cluster_name=${{ inputs.cluster-name }}" -var "offline_access_token=${{ inputs.rh-token }}" -var "htpasswd_password=dUmmyPassword$123!"

    - name: Terraform Apply Destroy
      shell: bash
      id: apply-destroy
      run: |
        cd .github/actions/rosa-delete-cluster/modules/rosa-hcp
        terraform apply -destroy -no-color rosa-destroy.plan
