name: Deploy ROSA HCP Cluster

description: |
  This GitHub Action automates the deployment of a ROSA (Red Hat OpenShift Service on AWS) cluster using Terraform with a dedicated namespace.
  This action will also install oc, awscli, rosa cli.
  This action also set the current kube context on the created namespace.

inputs:
  rh-token:
    description: 'Red Hat Hybrid Cloud Console Token'
    required: true
  cluster-name:
    description: 'Name of the ROSA cluster to deploy'
    required: true
  admin-password:
    description: 'Admin password for the ROSA cluster'
    required: true
  admin-username:
    description: 'Admin username for the ROSA cluster'
    required: true
  aws-region:
    description: 'AWS region where the ROSA cluster will be deployed'
    required: true
  namespace:
    description: 'Namespace to create in the ROSA cluster'
    required: true
  rosa-cli-version:
    description: 'Version of the ROSA CLI to use'
    required: true
    default: "latest"
  awscli-version:
    description: 'Version of the aws cli to use'
    required: true
    default: "1.32.105" # TODO: for all versions, update default one with renovate
  oc-version:
    description: 'Version of the oc cli to install'
    required: true
    default: "latest"
  openshift-version:
    description: 'Version of the OpenShift to install'
    required: true
    default: "4.15.11"
  replicas:
    description: 'Number of replicas for the ROSA cluster'
    required: true
    default: "2"
  s3-backend-bucket:
    description: 'Name of the S3 bucket to store Terraform state'
    required: true

outputs:
  openshift-server-api:
    description: 'The server API URL of the deployed ROSA cluster'
    value: ${{ steps.kube_config.outputs.cluster_api }}

  openshift-cluster-id:
    description: 'The ID of the deployed ROSA cluster'
    value: ${{ steps.apply.outputs.cluster_id }}

  terraform-state-url:
    description: 'URL of the Terraform state file in the S3 bucket'
    value: ${{ steps.set-terraform-variables.outputs.terraform-state-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install ROSA CLI
      shell: bash
      run: |
        curl -O "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/${{ inputs.rosa-cli-version }}/rosa-linux.tar.gz"
        tar -xvf rosa-linux.tar.gz
        sudo mv rosa /usr/local/bin/rosa
        rosa version

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Install oc CLI
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: ${{ inputs.oc-version }}

    - name: Login to Red Hat Hybrid Cloud Console
      shell: bash
      run: |
        rosa login --token=${{ inputs.rh-token }}
        rosa whoami

    - name: Verify and enable HCP ROSA on AWS Marketplace
      shell: bash
      run: |
        rosa verify quota --region="${{ inputs.aws-region }}"
        rosa verify permissions --region="${{ inputs.aws-region }}"
        rosa create account-roles --mode auto

    - name: Install aws-cli
      shell: bash
      run: |
        python3 -m pip install "awscli==${{ inputs.awscli-version }}"

    - name: Check if S3 bucket exists
      id: create-s3-bucket
      shell: bash
      run: |
        if aws s3api head-bucket --bucket ${{ inputs.s3-backend-bucket }} --region ${{ inputs.aws-region }} 2>/dev/null; then
          echo "Bucket already exists"
        else
          echo "Bucket does not exist, creating..."
          aws s3api create-bucket --bucket ${{ inputs.s3-backend-bucket }} --region ${{ inputs.aws-region }} --create-bucket-configuration LocationConstraint=${{ inputs.aws-region }}
        fi

        aws s3api put-public-access-block --bucket ${{ inputs.s3-backend-bucket }} --region ${{ inputs.aws-region }} --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

    - name: Set Terraform variables
      shell: bash
      id: set-terraform-variables
      run: |
        export TFSTATE_BUCKET="${{ inputs.s3-backend-bucket }}"
        export TFSTATE_REGION="${{ inputs.aws-region }}"
        export TFSTATE_KEY="tfstate-${{ inputs.cluster-name }}/${{ inputs.cluster-name }}.tfstate"
        echo "TFSTATE_BUCKET=${TFSTATE_BUCKET}" >> "$GITHUB_OUTPUT"
        echo "TFSTATE_REGION=${TFSTATE_REGION}" >> "$GITHUB_OUTPUT"
        echo "TFSTATE_KEY=${TFSTATE_KEY}" >> "$GITHUB_OUTPUT"

        terraform_state_url="s3://${TFSTATE_BUCKET}/${TFSTATE_KEY}"
        echo "terraform-state-url=${terraform_state_url}" >> "$GITHUB_OUTPUT"

    - name: Terraform Init
      shell: bash
      id: init
      run: |
        cd .github/actions/rosa-create-cluster/modules/rosa-hcp

        terraform init -backend-config="bucket=${{ steps.set-terraform-variables.outputs.TFSTATE_BUCKET }}" -backend-config="key=${{ steps.set-terraform-variables.outputs.TFSTATE_KEY }}" -backend-config="region=${{ steps.set-terraform-variables.outputs.TFSTATE_REGION }}"
        terraform validate -no-color

    - name: Terraform Plan
      shell: bash
      id: plan
      run: |
        cd .github/actions/rosa-create-cluster/modules/rosa-hcp
        terraform plan -no-color -out rosa.plan -var "cluster_name=${{ inputs.cluster-name }}" -var "replicas=${{ inputs.replicas }}" -var "htpasswd_password=${{ inputs.admin-password }}" -var "htpasswd_username=${{ inputs.admin-username }}" -var "offline_access_token=${{ inputs.rh-token }}" -var "openshift_version=${{ inputs.openshift-version }}"

    - name: Terraform Apply
      shell: bash
      id: apply
      run: |
        cd .github/actions/rosa-create-cluster/modules/rosa-hcp
        terraform apply -no-color rosa.plan

        export cluster_id="$(terraform output -raw cluster_id)"
        echo "cluster_id=$cluster_id" >> "$GITHUB_OUTPUT"

    - name: Retrieve cluster information
      shell: bash
      id: cluster_info
      run: |
        rosa describe cluster --output=json -c "${{ steps.apply.outputs.cluster_id }}"

    - name: Generate kubeconfig
      shell: bash
      id: kube_config
      run: |
        export server_api=$(rosa describe cluster --output=json -c "${{ steps.apply.outputs.cluster_id }}" | jq -r '.api.url')
        echo "server_api=$server_api" >> "$GITHUB_OUTPUT"

        oc login --username "${{ inputs.admin-username }}" --password "${{ inputs.admin-password }}" --server=$SERVER_API
        kubectl config rename-context $(oc config current-context) "${{ inputs.cluster-name }}"
        kubectl config use "${{ inputs.cluster-name }}"
        oc new-project "${{ inputs.namespace }}"
