---
# this manifest creates the database
apiVersion: batch/v1
kind: Job
metadata:
    name: create-setup-user-db
    labels:
        app: create-setup-user-db
spec:
    backoffLimit: 0
    template:
        spec:
            restartPolicy: Never
            containers:
                - name: create-setup-user-db
                  image: amazonlinux:latest
                  command:
                      - sh
                      - -c
                      - |
                        /bin/bash <<'EOF'
                        set -o pipefail

                        echo "Installing dependencies..."
                        yum install -y postgresql15

                        echo "Create keycloak user and associated database"
                        psql -h $AURORA_ENDPOINT -p $AURORA_PORT "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME password=$AURORA_PASSWORD" \
                          -c "CREATE DATABASE \"${DB_KEYCLOAK_NAME}\";" \
                          -c "CREATE USER \"${DB_KEYCLOAK_USERNAME}\" WITH LOGIN;" \
                          -c "GRANT ALL PRIVILEGES ON DATABASE \"${DB_KEYCLOAK_NAME}\" TO \"${DB_KEYCLOAK_USERNAME}\";" \
                          -c "GRANT rds_iam TO \"${CAMUNDA_KEYCLOAK_SERVICE_ACCOUNT_NAME}\";"

                        echo "Create identity user and associated database"
                        psql -h $AURORA_ENDPOINT -p $AURORA_PORT "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME password=$AURORA_PASSWORD" \
                          -c "CREATE DATABASE \"${DB_IDENTITY_NAME}\";" \
                          -c "CREATE USER \"${DB_IDENTITY_USERNAME}\" WITH LOGIN;" \
                          -c "GRANT ALL PRIVILEGES ON DATABASE \"${DB_IDENTITY_NAME}\" TO \"${DB_IDENTITY_USERNAME}\";" \
                          -c "GRANT rds_iam TO \"${CAMUNDA_IDENTITY_SERVICE_ACCOUNT_NAME}\";"

                        echo "Create webmodeler user and associated database"
                        psql -h $AURORA_ENDPOINT -p $AURORA_PORT "sslmode=require dbname=$AURORA_DB_NAME user=$AURORA_USERNAME password=$AURORA_PASSWORD" \
                          -c "CREATE DATABASE \"${DB_WEBMODELER_NAME}\";" \
                          -c "CREATE USER \"${DB_WEBMODELER_USERNAME}\" WITH LOGIN;" \
                          -c "GRANT ALL PRIVILEGES ON DATABASE \"${DB_WEBMODELER_NAME}\" TO \"${DB_WEBMODELER_USERNAME}\";" \
                          -c "GRANT rds_iam TO \"${CAMUNDA_WEBMODELER_SERVICE_ACCOUNT_NAME}\";"

                        EOF
                  env:
                      - name: AURORA_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: AURORA_ENDPOINT
                      - name: AURORA_PORT
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: AURORA_PORT
                      - name: AURORA_DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: AURORA_DB_NAME
                      - name: AURORA_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: AURORA_USERNAME
                      - name: AURORA_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: AURORA_PASSWORD
                      - name: DB_KEYCLOAK_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_KEYCLOAK_NAME
                      - name: DB_KEYCLOAK_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_KEYCLOAK_USERNAME
                      - name: CAMUNDA_KEYCLOAK_SERVICE_ACCOUNT_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: CAMUNDA_KEYCLOAK_SERVICE_ACCOUNT_NAME
                      - name: DB_IDENTITY_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_IDENTITY_NAME
                      - name: DB_IDENTITY_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_IDENTITY_USERNAME
                      - name: CAMUNDA_IDENTITY_SERVICE_ACCOUNT_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: CAMUNDA_IDENTITY_SERVICE_ACCOUNT_NAME
                      - name: DB_WEBMODELER_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_WEBMODELER_NAME
                      - name: DB_WEBMODELER_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: DB_WEBMODELER_USERNAME
                      - name: CAMUNDA_WEBMODELER_SERVICE_ACCOUNT_NAME
                        valueFrom:
                            secretKeyRef:
                                name: setup-db-secret
                                key: CAMUNDA_WEBMODELER_SERVICE_ACCOUNT_NAME
