name: Delete EKS resources

description: |
  This GitHub Action automates the deletion of EKS resources using a shell script.

inputs:
  tf-bucket:
    description: 'Bucket containing the resources states'
    required: true
  max-age-hours:
    description: 'Maximum age of resources in hours'
    required: false
    default: "20"
  target:
    description: 'Specify an ID to destroy specific resources or "all" to destroy all resources'
    required: true
    default: "all"
  temp-dir:
    description: 'Temporary directory prefix used for storing resource data during processing'
    required: false
    default: "./tmp/eks-cleanup/"

runs:
  using: 'composite'
  steps:
    - name: Delete resources
      id: delete_resources
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/destroy.sh "${{ inputs.tf-bucket }}" ${{ github.action_path }}/../../../modules/ "${{ inputs.temp-dir }}" ${{ inputs.max-age-hours }} ${{ inputs.target }}
