---
# Configuration documentation https://terraform-docs.io/user-guide/configuration/
formatter: "markdown table"  # Required
version: "" # version is managed by asdf

header-from: main.tf
footer-from: ""

recursive:
  enabled: false

content: |-
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
sections:
  hide: []
  show: []

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
