---
identityKeycloak:
    postgresql:
        enabled: false
    externalDatabase:
        # see https://artifacthub.io/packages/helm/bitnami/keycloak
        existingSecret: identity-keycloak-secret   # Name of an existing secret resource containing the database credentials
        existingSecretHostKey: host
        existingSecretPortKey: port
        existingSecretUserKey: user
        existingSecretDatabaseKey: database
        existingSecretPasswordKey: password

    auth:
        existingSecret: identity-secret-for-components

global:
    elasticsearch:
        enabled: false
    opensearch:
        enabled: true
        aws:
            enabled: false # we rely on anonymous auth, not irsa, basic auth is not supported on managed OpenSearch
        auth:
            username:
            password:
        url:
            protocol: https
            host: ${OPENSEARCH_HOST}
            # Amazon OpenSearch Service listens on port 443 opposed to the usual port 9200.
            port: 443

    identity:

        auth:
            publicIssuerUrl: http://localhost:8070/auth/realms/camunda-platform  # replace this with a port of your choice when you will do port forwarding

            zeebe:
                existingSecret:
                    name: identity-secret-for-components
            connectors:
                existingSecret:
                    name: identity-secret-for-components
            operate:
                redirectUrl: http://localhost:8081  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            tasklist:
                redirectUrl: http://localhost:8082  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            optimize:
                redirectUrl: http://localhost:8083  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            webModeler:
                redirectUrl: http://localhost:8084
            console:
                redirectUrl: http://localhost:8085
                existingSecret:
                    name: identity-secret-for-components

identity:
    fullURL: http://localhost:8069 # replace this with a port of your choice when you will do port forwarding

    externalDatabase:
        enabled: true
        host: ${DB_HOST}
        port: 5432
        username: ${DB_IDENTITY_USERNAME}
        database: ${DB_IDENTITY_NAME}
        existingSecret: identity-postgres-secret
        existingSecretPasswordKey: password

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        externalDatabase:
            url: jdbc:aws-wrapper:postgresql://${DB_HOST}:5432/${DB_WEBMODELER_NAME}
            user: ${DB_WEBMODELER_USERNAME}
            existingSecret: webmodeler-postgres-secret
            existingSecretPasswordKey: password
        mail:
            existingSecret: identity-secret-for-components # reference the smtp password
            fromAddress: changeme@example.com   # change this required value

optimize:
    migration:
        enabled: false

console:
    enabled: false # by default, console is not enabled

elasticsearch:
    enabled: false
