---
identityKeycloak:
    postgresql:
        enabled: false
    externalDatabase:
        host: ${DB_HOST}
        user: ${PG_USERNAME}
        password: ${PG_PASSWORD}
        database: ${DEFAULT_DB_NAME}

global:
    elasticsearch:
        enabled: false
    opensearch:
        enabled: true
        aws:
            enabled: true
        auth:
            username: ${OPENSEARCH_MASTER_USER}
            password: ${OPENSEARCH_MASTER_PASSWORD}
        url:
            protocol: https
            host: ${OPENSEARCH_HOST}
            # Amazon OpenSearch Service listens on port 443 opposed to the usual port 9200.
            port: 443

    ingress:
        enabled: true
        host: ${DOMAIN_NAME}
        tls:
            enabled: true
            secretName: camunda-c8-tls
        annotations:
            kubernetes.io/tls-acme: 'true'
    identity:
        auth:
            publicIssuerUrl: https://${DOMAIN_NAME}/auth/realms/camunda-platform
            operate:
                redirectUrl: https://${DOMAIN_NAME}/operate
            tasklist:
                redirectUrl: https://${DOMAIN_NAME}/tasklist
            optimize:
                redirectUrl: https://${DOMAIN_NAME}/optimize


elasticsearch:
    enabled: false

identity:
    contextPath: /identity
    fullURL: https://${DOMAIN_NAME}/identity

operate:
    contextPath: /operate

tasklist:
    contextPath: /tasklist

optimize:
    contextPath: /optimize
    migration:
        enabled: false

zeebeGateway:
    ingress:
        grpc:
            enabled: true
            host: zeebe.${DOMAIN_NAME}
            tls:
                enabled: true
                secretName: zeebe-c8-tls-grpc
            annotations:
                kubernetes.io/tls-acme: 'true'
    contextPath: /zeebe
