---
identityKeycloak:
    postgresql:
        enabled: false
    externalDatabase:
        host: ${DB_HOST}
        user: ${PG_USERNAME}
        database: ${DEFAULT_DB_NAME}
    extraEnvVars:
        - name: KEYCLOAK_EXTRA_ARGS
          value: --db-driver=software.amazon.jdbc.Driver --transaction-xa-enabled=false --log-level=INFO,software.amazon.jdbc:INFO
        - name: KEYCLOAK_JDBC_PARAMS
          value: wrapperPlugins=iam
        - name: KEYCLOAK_JDBC_DRIVER
          value: aws-wrapper:postgresql

global:
    elasticsearch:
        enabled: false
    opensearch:
        enabled: true
        aws:
            enabled: true
