---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@ab2672ba2fbed7e70e00087cbed14b9d4f923579 # 1.2.0
        secrets: inherit
