---
# desc: lint sanity check
name: lint

on:
  push:
  workflow_dispatch:


jobs:
  lint:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5

      - uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4
        name: Setup TFLint
        with:
          tflint_version: v0.50.3

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      - run: go install github.com/terraform-docs/terraform-docs@v0.17.0

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
