---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@bab24f9a0e9a49281a4c0d34d059b5edd73078e4 # 1.2.1
        secrets: inherit
