---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@feature/auto-update-renovate-doc
      # TODO: pin and change autofix actor
        with:
            autofix-actor: leiicamundi
        secrets: inherit
