---
name: Renovate Auto Merge

on:
    pull_request:

# limit to a single execution per ref of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    renovate-automerge:
        # TODO: temporary using a feature branch to unlock auto merge, please use a pinned version once it's merged.
        uses: camunda/infraex-common-config/.github/workflows/automerge-global.yml@fix/gh-tokens-and-major-merge
        secrets: inherit
