---
name: Renovate Auto Merge

on:
    pull_request:
        types: [opened, reopened, ready_for_review]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/automerge-global.yml@b9387e1aff56dd033a4caef687c6cb8d540cb7f9 # 1.2.1
        secrets: inherit
