---
name: Renovate Auto Merge

on:
    pull_request:

# limit to a single execution per ref of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    renovate-automerge:
        uses: camunda/infraex-common-config/.github/workflows/automerge-global.yml@ca5f4c53e82d4787cec72d6f3a177abaa59423b0 # 1.2.15
        secrets: inherit
